In [8]:
import numpy as np

#### Sets of scores from students, with each column grouped by subject matter.

In [31]:
A = np.array([[90, 80, 40],
              [90, 60, 80],
              [60, 50, 70],
              [30, 40, 70],
              [30, 20, 90]])

In [32]:
ones = np.ones([5, 5])
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

#### Dot product of ones matrix and A matrix gives total marks for the particular subject

In [33]:
deviation =ones.dot(A)
deviation

array([[300., 250., 350.],
       [300., 250., 350.],
       [300., 250., 350.],
       [300., 250., 350.],
       [300., 250., 350.]])

In [34]:
length=len(A)
length

5

#### Total subject marks divided by total subject, thus giving the average marks for each subject. 

#### It is then subtracted from matrix A to give the deviation

In [27]:
deviation=A-(deviation/length)
deviation

array([[ 30.,  30., -30.],
       [ 30.,  10.,  10.],
       [  0.,   0.,   0.],
       [-30., -10.,   0.],
       [-30., -30.,  20.]])

#### The dot product of A transpose A produces the covariance matrix.

In [35]:
covariance = deviation.T.dot(deviation)
covariance

array([[450000., 375000., 525000.],
       [375000., 312500., 437500.],
       [525000., 437500., 612500.]])